### ISSUE TITLE
No dirt background, no font and other errors - Fedora 40

### ISSUE THREAD

**Issue by Player6734** [nikp123/minecraft-plymouth-theme#3]
Hi, 
First of all thank you for this plymouth theme.
I encounter several errors when trying to install it, i would like to make multiple issues but i can't really pin-point where the issues come from. So i'll give the symptoms and what i tried. 
when i run `sudo ./install.sh`
```
'./font/config/00-minecraft.conf' -> '/etc/fonts/conf.d/00-minecraft.conf'
'./font/Minecraft.otf' -> '/usr/share/fonts/OTF/'
cp: cannot create regular file '/usr/share/fonts/OTF/': Not a directory
'./plymouth/mc.script' -> '/usr/share/plymouth/themes/mc/mc.script'
'./plymouth/mc.plymouth' -> '/usr/share/plymouth/themes/mc/mc.plymouth'
'./plymouth/progress_bar.png' -> '/usr/share/plymouth/themes/mc/progress_bar.png'
'./plymouth/progress_box.png' -> '/usr/share/plymouth/themes/mc/progress_box.png'
WARNING: The convert command is deprecated in IMv7, use "magick"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/usr/share/plymouth/themes/mc/padlock/1.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/usr/share/plymouth/themes/mc/padlock/2.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/usr/share/plymouth/themes/mc/padlock/3.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/usr/share/plymouth/themes/mc/padlock/4.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/usr/share/plymouth/themes/mc/padlock/5.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/usr/share/plymouth/themes/mc/padlock/6.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/usr/share/plymouth/themes/mc/bar/1.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/usr/share/plymouth/themes/mc/bar/2.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/usr/share/plymouth/themes/mc/bar/3.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/usr/share/plymouth/themes/mc/bar/4.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/usr/share/plymouth/themes/mc/bar/5.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/usr/share/plymouth/themes/mc/bar/6.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick"

WARNING: The convert command is deprecated in IMv7, use "magick"

WARNING: The convert command is deprecated in IMv7, use "magick"

WARNING: The convert command is deprecated in IMv7, use "magick"

WARNING: The convert command is deprecated in IMv7, use "magick"

WARNING: The convert command is deprecated in IMv7, use "magick"

WARNING: The convert command is deprecated in IMv7, use "magick"

WARNING: The convert command is deprecated in IMv7, use "magick"

WARNING: The convert command is deprecated in IMv7, use "magick"

WARNING: The convert command is deprecated in IMv7, use "magick"

WARNING: The convert command is deprecated in IMv7, use "magick"

WARNING: The convert command is deprecated in IMv7, use "magick"

'./dracut/99-minecraft-plymouth.conf' -> '/etc/dracut.conf.d/99-minecraft-plymouth.conf'

```
i attempted to modify the convert command thinking this would fix it but i'm not familiat with ImageMagick, here is the command i tried: `magick ./plymouth/dirt.png -strip -channel R -evaluate multiply .2509803922 -channel G -evaluate multiply .2509803922 -channel B -evaluate multiply .2509803922 -interpolate Nearest -filter point -resize "$i"00% ${PLYMOUTH_THEME_BASEDIR}/dirt/"${i}".png`

after this, `sudo plymouth-set-default-theme -R mc` outputs the following:
```
dracut-install: ERROR: installing '/usr/lib/plymouth/label.so'
dracut-install: ERROR: installing '/usr/lib/plymouth/text.so'
dracut-install: ERROR: installing '/usr/share/fonts/OTF/Minecraft.otf'
dracut[E]: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.3XaCDN/initramfs -a /usr/lib/plymouth/label.so /usr/lib/plymouth/text.so /usr/share/fonts/OTF/Minecraft.otf /etc/fonts/fonts.conf /etc/fonts/conf.d/00-minecraft.conf
```

the result is a gray plymouth theme with the text, loading screen and even "Booting OS" showing up but not the dirt in the background. I'm not sure if the font is the correct one but i doubt it is as it's pretty round.
I cannot take screenshots of course but if needed i can take pictures with my phone if it would help troubleshooting.

Thanks for any help

**Comment by nikp123** [comment]
Thats because the imagemagick's convert command was deprecated, can you share what system you're running. Seemingly imagemagick had a breaking change.

**Comment by Player6734** [comment]
I am running fedora 40 on kde with wayland

The font is also not being applied, `cp: cannot create regular file '/usr/share/fonts/OTF/': Not a directory`, how could i fix this?

**Comment by nikp123** [comment]
> The font is also not being applied, `cp: cannot create regular file '/usr/share/fonts/OTF/': Not a directory`, how could i fix this?

That's just the directory missing. Add it manually, and I will fix it in the script.

**Comment by nikp123** [comment]
@Player6734 pushed the new install script which also uses the ``magick`` command.

**Comment by Player6734** [comment]
Thank you very much for your help, I made the /usr/share/fonts/OTF/ directory and that was it fixed.

However after deleting the themes folder and going through the install process again I still don't have the background image

**Comment by nikp123** [comment]
> However after deleting the themes folder and going through the install process again I still don't have the background image

Testing this on a clean voidlinux machine confirms that it's not the script in question. Are you sure you included the proper libraries for your distro?

**Comment by nikp123** [comment]
Plus I pushed a commit that might fix the problem.

**Comment by Player6734** [comment]
Thank you for testing it, I had `plymouth` installed but needed `plymouth-devel`, i am still getting error messages when running  `sudo plymouth-set-default-theme -R mc` but it looks like those are nothing big.


here are the error messages i have that i plan on living with:
```
dracut-install: ERROR: installing '/usr/lib/plymouth/script.so'
dracut-install: ERROR: installing '/usr/lib/plymouth/label.so'
dracut-install: ERROR: installing '/usr/lib/plymouth/text.so'
dracut[E]: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.vgtxHS/initramfs -a /usr/lib/plymouth/script.so /usr/lib/plymouth/label.so /usr/lib/plymouth/text.so /usr/share/fonts/OTF/Minecraft.otf /etc/fonts/fonts.conf /etc/fonts/conf.d/00-minecraft.conf
```

**Comment by Player6734** [comment]
so, solution for me was to create the /usr/share/fonts/OTF/ directory, then install `plymouth-devel`
```
sudo mkdir /usr/share/fonts/OTF/
sudo dnf install -y plymouth-devel
```
